### ISSUE TITLE
FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.

### ISSUE THREAD

**Issue by stefee** [open-telemetry/opentelemetry-js-contrib#1275]
### What version of OpenTelemetry are you using?

`@opentelemetry/instrumentation-fastify@0.30.1`

### What version of Node are you using?

`v16.14.2`

### What did you do?

Node auto instrumentation on a Fastify application

### What did you expect to see?

No deprecation notices

### What did you see instead?

```
FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.
```

### Additional context

Request `.context` is used here:

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/aff84bba1d391ec2061b8d0121ac8dd36fc1980c/plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts#L262

**Comment by stefee** [comment]
Bump

**Comment by Bruno-DaSilva** [comment]
bump :(

**Comment by Uzlopak** [comment]
To fix the issue in opentelemetry, you would need to patch 

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/154b30bc98ff0b848348faa18197eb7f11dcbdc4/plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts#L263

There I think you would need to change it to:
```js
      const handlerName = (((request as any).routeConfig || {})?.name || '').substr(6);
```

**Comment by Uzlopak** [comment]
Or maybe even simpler:

```js
      const handlerName = (request as any)?.routeConfig?.name?.substr(6) || '';
```

I did not test it.

**Comment by freakyfelt** [comment]
Alas that one won't work as the routeConfig does not expose the handler, so we're waiting for https://github.com/fastify/fastify/pull/4470

**Comment by Uzlopak** [comment]
I closed the remaining issues in the fastify PR and requested review by @eomm

**Comment by drewcorlin1** [comment]
Wouldn't this be the most type safe way to fix the warning?

```typescript
const handlerName = `${request.routeOptions.method} ${request.routeOptions.url}`;
```

**Comment by freakyfelt** [comment]
> Wouldn't this be the most type safe way to fix the warning?

This particular label is for the name of the handler (e.g. the name of the function), so changing it would be a breaking a change

**Comment by SimenB** [comment]
Change in Fastify landed now (:tada:), so once that's released it's hopefully not too difficult to migrate the instrumentation.

>This particular label is for the name of the handler (e.g. the name of the function), so changing it would be a breaking a change

The instrumentation is experimental (`v0.x`), so I don't think that's a huge concern? Not sure how these things are managed.

**Comment by Travispersson** [comment]
> Change in Fastify landed now (🎉), so once that's released it's hopefully not too difficult to migrate the instrumentation.
> 
> > This particular label is for the name of the handler (e.g. the name of the function), so changing it would be a breaking a change
> 
> The instrumentation is experimental (`v0.x`), so I don't think that's a huge concern? Not sure how these things are managed.

It's now available in the latest [Fastify release](https://github.com/fastify/fastify/releases/tag/v4.23.0) that was released today 🥳

**Comment by Travispersson** [comment]
Hmm, just a note, I'm getting these deprecation warnings as well from this instrumentation lib
``` 
[FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
```

Could be this line? https://github.com/open-telemetry/opentelemetry-js-contrib/blob/b10224bc9be3b82fd2c8d60bcd0604b5cc0ad725/plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts#L272

**Comment by Uzlopak** [comment]
yes

**Comment by mateus4k** [comment]
> ```
> [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
> ```

Is there any PR updating this?

**Comment by Travispersson** [comment]
> > ```
> > [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
> > ```
> 
> Is there any PR updating this?

https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1679 
Yep a fix was released ⭐

**Comment by mateus4k** [comment]
Thanks, @Travispersson!

**Comment by omBratteng** [comment]
Still getting this error
```
(node:9) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
```

We are using the latest version of the intrumentation

https://github.com/dailydotdev/daily-api/blob/dc3bbecd7c04984a60a224b19ae9752102caf09e/package.json#L48

and version 4.24.2 of fastify

https://github.com/dailydotdev/daily-api/blob/dc3bbecd7c04984a60a224b19ae9752102caf09e/package.json#L71

**Comment by omBratteng** [comment]
So digging a bit further into it, I think it might when the requests are to not found pages. but then both `request.routeOptions.url` and `request.routerPath` are undefined.

**Comment by Wazbat** [comment]
I can confirm that I'm also still getting these errors
```
(node:1) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
```
`fastify` `4.24.3` and `@opentelemetry/instrumentation-fastify` `0.32.3`

**Comment by SimenB** [comment]
That's separate from the one in the OP (which hss been fixed, from what I can tell). Might be worth its own issue? Or just somebody sending a PR 🙂

**Comment by omBratteng** [comment]
I've split it into a separate issue here #1757

**Comment by trentm** [comment]
I believe this was fixed in #1679, when one is using fastify `>=4.23.0` (when the `request.routeOptions.handler` option was made available).  When using earlier fastify versions there is nothing the instrumentation can do to avoid the deprecation warning.

I have a PR up for the separate #1757 issue.

**Comment by trentm** [comment]
> I believe this was fixed in #1679,

^ @pichlermarc I think you can close this issue.
