### ISSUE TITLE
vite build for browser pulling in node built-in modules

### ISSUE THREAD

**Issue by vidarc** [open-telemetry/opentelemetry-js-contrib#1892]
### What version of OpenTelemetry are you using?

Using latest versions of packages.

### What version of Node are you using?

Node 20

### What did you do?

Running `vite build` (using version 4 of vite) will throw the following error. 

```
"normalize" is not exported by "__vite-browser-external", imported by "../../node_modules/@opentelemetry/instrumentation/build/esm/instrumentationNodeModuleFile.js".
file: .../node_modules/@opentelemetry/instrumentation/build/esm/instrumentationNodeModuleFile.js:16:9
14:  * limitations under the License.
15:  */
16: import { normalize } from 'path';
             ^
17: var InstrumentationNodeModuleFile = /** @class */ (function () {
18:     function InstrumentationNodeModuleFile(name, supportedVersions, patch, unpatch) {
error during build:
RollupError: "normalize" is not exported by "__vite-browser-external", imported by "../../node_modules/@opentelemetry/instrumentation/build/esm/instrumentationNodeModuleFile.js".
```

You will also get a warning about

```
[plugin:vite:resolve] Module "path" has been externalized for browser compatibility, imported by ".../node_modules/@opentelemetry/instrumentation/build/esm/instrumentationNodeModuleFile.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

### What did you expect to see?

I would expect browser based builds to not pull in any node built-ins, so that there is no need to polyfill them and thus help to keep bundle sizes smaller.

**Comment by lnmp4000** [comment]
Same issue using rollup.js

```
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
path (imported by "node_modules/@opentelemetry/instrumentation/build/esm/instrumentationNodeModuleFile.js")
```

**Comment by pichlermarc** [comment]
This is fixed by https://github.com/open-telemetry/opentelemetry-js/pull/4386, the new release will take care of it (we plan to release early next week)

**Comment by imWildCat** [comment]
Hi @pichlermarc ! Good job!

I tried to upgrade all open telemetry packages but still seeing this error from `@opentelemetry/api@1.7.0` which contains the bad version, `'@opentelemetry/instrumentation': 0.46.0(@opentelemetry/api@1.7.0)`

```
  /@opentelemetry/auto-instrumentations-web@0.35.0(@opentelemetry/api@1.7.0)(zone.js@0.11.4):
    resolution: {integrity: sha512-JbbuOBhIfOSTOtrNU0ovgTIh3Wz05/y3RhPpLjhJBWF6M2h1u2tMjsod1/JUgrUn3mAAOLMmy1OJB23Ps0dDRg==}
    engines: {node: '>=14'}
    peerDependencies:
      '@opentelemetry/api': ^1.3.0
      zone.js: 0.11.4
    dependencies:
      '@opentelemetry/api': 1.7.0
      '@opentelemetry/instrumentation': 0.46.0(@opentelemetry/api@1.7.0)
      '@opentelemetry/instrumentation-document-load': 0.34.1(@opentelemetry/api@1.7.0)
      '@opentelemetry/instrumentation-fetch': 0.46.0(@opentelemetry/api@1.7.0)
      '@opentelemetry/instrumentation-user-interaction': 0.34.1(@opentelemetry/api@1.7.0)(zone.js@0.11.4)
      '@opentelemetry/instrumentation-xml-http-request': 0.46.0(@opentelemetry/api@1.7.0)
      zone.js: 0.11.4
    transitivePeerDependencies:
      - supports-color
    dev: false
```

**Comment by imWildCat** [comment]
@pichlermarc got it! thank you so much!

**Comment by pq43** [comment]
+1 on this, tysm for getting to it so fast!

**Comment by pichlermarc** [comment]
We finally managed to get everything sorted out. Sorry that this took so long. 
It should be fixed in the latest release.

**Comment by alexandprivate** [comment]
is this solved? I still experiencing the same issue with the latest version, in my case all packages are installed by faro-react but I manually added instrumentation, api and sdk-node, am I missing something?

**Comment by pichlermarc** [comment]
> is this solved? I still experiencing the same issue with the latest version, in my case all packages are installed by faro-react but I manually added instrumentation, api and sdk-node, am I missing something?

It should be. I'm not sure how faro works, but I think it'll pull in older versions of `@opentelemetry/instrumentation` as the dependencies for the package will pull in `^0.34.0`, but the latest is `0.35.0` which does not match that range. I'm sure they'll bump the dependencies and release soon.

**Comment by alexandprivate** [comment]
Quick update, overwriting works thanks, faro-web-tracking keeps pulling 0.34.0

**Comment by eskirk** [comment]
@alexandprivate sorry for the delay on the Faro side of things - we will be bumping dependencies and cutting a release today/tomorrow. 

thanks @pichlermarc for keeping us up to date and getting this fix rolled out 🙏🏼

**Comment by bdegannes** [comment]
Still experiencing this issue in **2025** with packages that claim browser support but fail during Vite builds.

**Affected packages:**
- `@opentelemetry/exporter-trace-otlp-http@0.201.1`
- `@opentelemetry/exporter-logs-otlp-http@0.201.0` 
- `@opentelemetry/auto-instrumentations-web@0.46.0`

**Errors:**
```
Module "stream" has been externalized for browser compatibility
Module "http" has been externalized for browser compatibility  
Module "perf_hooks" has been externalized for browser compatibility
Uncaught ReferenceError: process is not defined
```

**Impact:** These packages require extensive Node.js polyfills to work in browsers, despite being documented as browser-compatible. This blocks production browser applications from using OpenTelemetry's official OTLP exporters.

**Root cause:** OTLP exporters use Node.js modules (`http`, `stream`, `perf_hooks`) instead of browser APIs (`fetch`, `ReadableStream`, `performance`).

**Environment:** Vite 6.1.1, React SPA with SSR, Node.js 23.3.0

Would appreciate guidance on browser support or recommendations for browser observability.

**Comment by bdegannes** [comment]
Hello, I am still experiencing this issue with packages that should have browser support but fail during Vite builds.

**Affected packages:**
- `@opentelemetry/exporter-trace-otlp-http@0.201.1`
- `@opentelemetry/exporter-logs-otlp-http@0.201.0` 
- `@opentelemetry/auto-instrumentations-web@0.46.0`

**Errors:**
```
Module "stream" has been externalized for browser compatibility
Module "http" has been externalized for browser compatibility  
Module "perf_hooks" has been externalized for browser compatibility
Uncaught ReferenceError: process is not defined
```

**Impact:** These packages require extensive Node.js polyfills to work in browsers, despite being documented as browser-compatible. This blocks production browser applications from using OpenTelemetry's official OTLP exporters.

**Root cause:** OTLP exporters use Node.js modules (`http`, `stream`, `perf_hooks`) instead of browser APIs (`fetch`, `ReadableStream`, `performance`).

**Environment:** Vite 6.1.1, React SPA with SSR, Node.js 23.3.0

Would appreciate guidance or recommendations for browser observability.
